/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/screens/onboarding/Onboarding2`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/constants/TypeStyles`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/peepee/explore`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/peepee/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/HomeNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/RootNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/onboarding/Onboarding1`; params?: Router.UnknownInputParams; } | { pathname: `/screens/onboarding/Welcome`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/Home`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/onboarding/Onboarding2`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/constants/TypeStyles`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/hooks/useThemeColor`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/hooks/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/hooks/useColorScheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/peepee/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/../frontend/peepee/index`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/HomeNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/RootNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/onboarding/Onboarding1`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/onboarding/Welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/tabs/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/screens/onboarding/Onboarding2${`?${string}` | `#${string}` | ''}` | `/../frontend/constants/Colors${`?${string}` | `#${string}` | ''}` | `/../frontend/constants/TypeStyles${`?${string}` | `#${string}` | ''}` | `/../frontend/hooks/useThemeColor${`?${string}` | `#${string}` | ''}` | `/../frontend/hooks/useColorScheme${`?${string}` | `#${string}` | ''}` | `/../frontend/hooks/useColorScheme.web${`?${string}` | `#${string}` | ''}` | `/../frontend/peepee/explore${`?${string}` | `#${string}` | ''}` | `/../frontend/peepee/index${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/navigation/HomeNavigator${`?${string}` | `#${string}` | ''}` | `/navigation/RootNavigator${`?${string}` | `#${string}` | ''}` | `/screens/onboarding/Onboarding1${`?${string}` | `#${string}` | ''}` | `/screens/onboarding/Welcome${`?${string}` | `#${string}` | ''}` | `/screens/tabs/Home${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/screens/onboarding/Onboarding2`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/constants/TypeStyles`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/peepee/explore`; params?: Router.UnknownInputParams; } | { pathname: `/../frontend/peepee/index`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/HomeNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/RootNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/screens/onboarding/Onboarding1`; params?: Router.UnknownInputParams; } | { pathname: `/screens/onboarding/Welcome`; params?: Router.UnknownInputParams; } | { pathname: `/screens/tabs/Home`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
